"""
LaTeX Table Generator for main.tex Tables 3 (ASR) & 4 (TSR).

Reviewer 2, point 3: report mean +/- std across 3-5 seeds instead of a
single pass. Reads a multi_seed_summary_*.json produced by
benchmark_evaluator.py and emits ready-to-paste LaTeX table body rows in
the same column order as main.tex's existing Table 3/4 (SecEval, LLMSec,
SecBench, CyberSec, CyberBench, HarmBench, FORMAI, ACSE-Eval, CyberSOCEval,
SECURE), restricted to the main-table approach set (static /
static+persona+safety / suicide-EPD per SLM, plus the two legacy LLM
baseline rows).

Usage:
    python3 analysis/generate_latex_tables.py \
        report-output/ghost_agents/benchmark_results/multi_seed_summary_<id>.json
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.ghost_agents.approach_evaluation.approaches import MAIN_TABLE_APPROACH_NAMES

BENCHMARK_COLUMN_ORDER = [
    "SecurityEval", "LLMSecEval", "SecBench", "CyberSecEval", "CyberBench",
    "HarmBench", "FORMAI", "ACSE-Eval", "CyberSOCEval", "SECURE",
]

EPD_ROW_SUFFIX = " (EPD)"


def _escape(name: str) -> str:
    return name.replace("_", "\\_")


def _row_label(name: str) -> str:
    label = _escape(name)
    if name.endswith("_suicide"):
        label += EPD_ROW_SUFFIX
    return label


def _model_prefix(name: str) -> str:
    return name.split("_static")[0].split("_suicide")[0]


def build_table(multi_seed_summary: dict, metric_key: str) -> str:
    """metric_key: 'asr_display' or 'tsr_display' (mean$\\pm$std strings)."""
    per_benchmark = multi_seed_summary.get("per_benchmark", {})
    seeds = multi_seed_summary.get("seeds", [])
    n_seeds = multi_seed_summary.get("n_seeds", len(seeds) or 1)

    lines = [
        f"% Auto-generated by analysis/generate_latex_tables.py",
        f"% n_seeds={n_seeds}, seeds={seeds}. Values are mean$\\pm$std (\\%) across seeds.",
    ]

    prev_prefix = None
    for name in MAIN_TABLE_APPROACH_NAMES:
        prefix = _model_prefix(name)
        if prev_prefix is not None and prefix != prev_prefix:
            lines.append(r"\hline")
        prev_prefix = prefix

        cells = []
        for bench in BENCHMARK_COLUMN_ORDER:
            entry = per_benchmark.get(bench, {}).get(name)
            cells.append(entry[metric_key] if entry else "-")
        lines.append(f"{_row_label(name)} & " + " & ".join(cells) + r" \\")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate LaTeX Table 3/4 rows from a multi-seed summary")
    parser.add_argument("multi_seed_summary")
    parser.add_argument("--out-dir", default="report-output/ghost_agents/latex_tables")
    args = parser.parse_args()

    with open(args.multi_seed_summary) as f:
        summary = json.load(f)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    asr_table = build_table(summary, "asr_display")
    tsr_table = build_table(summary, "tsr_display")

    (out_dir / "table3_asr_rows.tex").write_text(asr_table + "\n")
    (out_dir / "table4_tsr_rows.tex").write_text(tsr_table + "\n")

    print(f"Wrote {out_dir / 'table3_asr_rows.tex'}")
    print(f"Wrote {out_dir / 'table4_tsr_rows.tex'}")
    print(
        "\nPaste these rows into main.tex's Table 3 / Table 4 tabular bodies "
        "(between the existing \\hline separators), replacing the single-pass values."
    )


if __name__ == "__main__":
    main()
